name: GoldorNetworkUHC
main: com.goldornetwork.uhc.UHC
load: startup
author: g0ldmanpox
description: This is property of GoldorNetwork.
version: 1.1
commands:
   start:
      description: Use this to start the match!
      usage: /<command> 
   cancel:
      description: Use this to cancel the match!
      usage: /<command> 
   create:
      description: Use this to create a team!
      usage: /<command> 
   join:
      description: Use this to either join a team or join the FFA!
      usage: /<command> [team] 
      aliases: [j]
   leave:
      description: Use this to leave a team or the game!
      usage: /<command> [option] 
      aliases: [l]
   invite:
      description: Use this to invite a player to your team!
      usage: /<command> [player]  
      aliases: [i]
   uninvite:
      description: Use this to uninvite a player to your team!
      usage: /<command> [player]
      aliases: [ui] 
   render:
      description: Use this to render the world!
      usage: /<command> [world] [radius]
   vote:
      description: Use this to vote for a poll!
      usage: /<command> [option]     
